name: code-quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python ${{ matrix.python.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          set -e;
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to $PATH
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.venv
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-

      # Install dependencies if they're not cached or poetry.lock has changed
      - name: Install dependencies
        if: steps.cache-deps.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run black
        run: poetry run black py_pong

      - name: Run pylint
        run: poetry run mypy py_pong

      - name: Run mypy
        run: poetry run mypy py_pong
